#include <LPC17xx.h>

void Fc_bluetooth_communication(void){
	
	LPC_SC->PCONP|=(0x1<<25);
	LPC_SC->PCLKSEL1=(LPC_SC->PCLKSEL1&~(0x3<<18))|(0x1<<18);	//	CONFIGURATE CLOCK OF PHERIPERAL UART3 TO =CCLK=100MHZ
	LPC_UART3->LCR=(LPC_UART3->LCR&~(0x7F))|(0x3)|(0x1<<7);	//	WORD LENGHT 8=CHAR,STOP BIT & PARITY & BREAK CONTROL TO 0, ENABLE DIVISOR LACH
	LPC_UART3->DLM=2;	//	EXPRESION USED TO TAKE THE BAUD RATE IN PAGE N323 WITH RESET VALUE OF DIVADD=0/MULVAAL=1
	LPC_UART3->DLL=139;
	LPC_UART3->LCR&=~(0x1<<7);	//	DISABLE DIVISOR LACH
	LPC_UART3->FCR=(LPC_UART3->FCR&~(0xFF))|(0x7);	//	ENABLE FIFO AND RESET FIFO RX/TX, RX TRIGGER LEVEL 0 INTERRUPT FOR EACH CHAR 
	
	LPC_UART3->IER|=(0x1);	//	ENABLE INTERRUPTION
}
