#include <LPC17xx.h>
#define T_ADC 0.1f

void Fc_config_TIMER(void){
	
	//TIMER0 FOR ADC CONVERSIONS AND SIGNAL GENERATOR DAC
	LPC_SC->PCONP|=(1<<1);	//	START TIMER0 
	LPC_SC->PCLKSEL0&=~(0x3<<2);	//	FTIMER1 FCLK/4
	LPC_TIM0->TCR=(0x1<<1);	//	RESET TIMER0 COUNTER AND PRESCALER AND DISABLE
	LPC_TIM0->PR=0;
	LPC_TIM0->CTCR&=0x0;	//	INCREMENT TC IN TIMER MODE
	LPC_TIM0->MCR|=(0x3<<6)|(0x1);	//	RESET TC WHEN MR2 AND INTERRUPT ON MR2 AND MR0
	LPC_TIM0->MR2=12499999;	//	0.5 SECS WITH EACH NOTE
	LPC_TIM0->MR1=12499999;	//	CONVERSION ADC 1 SEC(TOGGLE 0.5-0.5)
	LPC_TIM0->MR0=4788;	//	START WITH DO	20 SAMPLES
	LPC_TIM0->EMR|=(0x2|(0x3<<6));
	LPC_TIM0->IR=0x3F;
	LPC_TIM0->TCR=0x1;	//	START TIMER

	//TIMER1 TAKE THE FREQENCY OF MOTOR1
	LPC_SC->PCONP|=(1<<2)|(1<<22)|(1<<23);	//	START TIMER1 AND TIMER2
	LPC_SC->PCLKSEL0=(LPC_SC->PCLKSEL0&~(0x3<<4))|(0x2<<4);		//	FTIMER1 FCLK/2
	LPC_TIM1->TCR=(0x1<<1);	//	RESET TIMER1 COUNTER AND PRESCALER AND DISABLE
	LPC_TIM1->PR=0x1388;	//	5000=1TC
	LPC_TIM1->CTCR&=~(0x3);	//	INCREMENT TC WITH PCK FREQENCY (TIMER MODE)
	LPC_TIM1->CCR|=0x5;	//	LOAD THE VALUE OF TC ON CR0 AND GENERATE INTERRUPT RISING EDGE
	LPC_TIM1->IR=0x3F;
	LPC_TIM1->TCR=0x1;	//	START TIMER

	//TIMER2 TAKE THE FREQENCY OF MOTOR2
	LPC_SC->PCLKSEL1=(LPC_SC->PCLKSEL1&~(0x3<<12))|(0x2<<12);	//	FTIMER2 FCLK/2
	LPC_TIM2->TCR=(0x1<<1);	//	RESET TIMER1 COUNTER AND PRESCALER AND DISABLE
	LPC_TIM2->PR=0x1388;	//	5000=1TC
	LPC_TIM2->CTCR&=~(0xF);	//	INCREMENT TC WITH PCK FREQENCY (TIMER MODE) AND USED CAP1.0 PIN INPUT
	LPC_TIM2->CCR|=0x5;	//	LOAD THE VALUE OF TC ON CR0 AND GENERATE INTERRUPT RISING EDGE
	LPC_TIM2->IR=0x3F;
	LPC_TIM2->TCR=0x1;	//	START TIMER

	//TIMER3	SET DISTANCE
	LPC_SC->PCLKSEL1=(LPC_SC->PCLKSEL1&~(0x3<<14))|(0x2<<14);	//	FTIMER2 FCLK/2
	LPC_TIM3->TCR=(0x1<<1);	//	RESET TIMER3 COUNTER AND PRESCALER AND DISABLE
	LPC_TIM3->CTCR=(LPC_TIM2->CTCR&~(0xF))|(0x3);	//	INCREMENT TC WITH BOTH EDGES (COUNTER MODE) AND USED CAP3.0 PIN INPUT
	LPC_TIM3->MCR=0x3;	//	CLEAR COUNTER TRIGGER INTERRUPT ON MR0 MATCH 
	LPC_TIM3->IR=0x3F;
	LPC_TIM3->TCR=0x1;	//	TIMER COUNTER AND PRESCALER ENABLE TO COUNTING	
}
