#include <LPC17xx.h>

void Fc_reset_Tc(void){
	LPC_TIM1->TCR=(0x1);	//	TIMER COUNTER AND PRESCALER ENABLE TO COUNTING
	LPC_TIM2->TCR=(0x1);	//	TIMER COUNTER AND PRESCALER ENABLE TO COUNTING
	NVIC_EnableIRQ(TIMER1_IRQn);
	NVIC_EnableIRQ(TIMER2_IRQn);
}
