#include <LPC17xx.h>

void usb_cfg(void){
	
	LPC_SC->PCONP|=(0x1<<3);
	LPC_SC->PCLKSEL0=(LPC_SC->PCLKSEL0&~(0x3<<6))|(0x1<<6);	//	CONFIGURATE CLOCK OF PHERIPERAL UART0 TO =CCLK=100MHZ
	LPC_UART0->LCR=(LPC_UART0->LCR&~(0x7F))|(0x3)|(0x1<<7);	//	WORD LENGTH 8=CHAR,STOP BIT & PARITY & BREAK CONTROL TO 0, ENABLE DIVISOR LACH
	LPC_UART0->DLM=2;	//	EXPRESION USED TO TAKE THE BAUD RATE IN PAGE N323 WITH RESET VALUE OF DIVADD=0/MULVAAL=1
	LPC_UART0->DLL=139;
	LPC_UART0->LCR&=~(0x1<<7);	//	DISABLE DIVISOR LACH
	LPC_UART0->FCR=(LPC_UART0->FCR&~(0xFF))|(0x7);	//	ENABLE FIFO AND RESET FIFO RX/TX, RX TRIGGER LEVEL 0 INTERRUPT FOR EACH CHAR 
	
	LPC_UART0->IER|=(0x1);	//	ENABLE INTERRUPTION
}
